### ISSUE TITLE
Staff status uses default (short) API token expiry

### ISSUE THREAD

**Issue by HeloiseS** [genghisken/psat-server-web#38]
Me and @genghisken made groups for the live server but left the VRA and ourselves (and you @jackleland)  as staff.

Then we realised that the staff tokens didn't have access: because they use the default expiry which is 1 day. 

Would if be possible to make staff status have a very long expiry (e.g. 30 years) so that status trumps all others?
Or do we think that's not a good idea?

**Comment by jackleland** [comment]
A couple of options: 
- We could make a 'staff group' which has very long token expiry time and add the staff members to it. This is available with the current state of the repo without modifications
- I can change the authentication check to not check expiry time for staff members, shouldn't take long but will be a PR

**Comment by jackleland** [comment]
This of course does mean that if a staff token gets compromised then the owner of that key will always be able to access the api with write permissions, which obviously isn't great security-wise

**Comment by HeloiseS** [comment]
Isn't that true if all the things we give a stupid long life to the token?

**Comment by genghisken** [comment]
Maybe we just live with the fact that staff members don't automatically get access to the API & add them to the 30 year expiry group that we just created. I'm happy with that situation.
