### ISSUE TITLE
QUESTION: Are the machine learning scores for an individual stamp or mean of entire set of stamps for each object?

### ISSUE THREAD

**Issue by thespacedoctor** [genghisken/psat-server-web#5]
These scores:

[![](https://live.staticflickr.com/65535/51652916980_5341d61fd7_z.png)](https://live.staticflickr.com/65535/51652916980_5341d61fd7_o.png)

**Comment by genghisken** [comment]
Median score for the 4 to 6 stamps generated for each object.

**Comment by thespacedoctor** [comment]
Thanks Ken!
