### ISSUE TITLE
Orient the astrometry RMS plot to match ATLAS stamp and Aldadin orientation

### ISSUE THREAD

**Issue by thespacedoctor** [genghisken/psat-server-web#6]
It would be neat to have all resources orientated the same way. This would make it clearer as to where large clusters of green detections originate from. In the [example below](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1180041350055217600/) the cluster to the bottom right of the RMS plot originates from the bright star to the north-east of the detection location. 

[![](https://live.staticflickr.com/65535/51654759585_a5d8c4ee23_z.png)](https://live.staticflickr.com/65535/51654759585_a5d8c4ee23_o.png)

**Comment by genghisken** [comment]
Fixed.

![Screenshot 2021-11-22 at 17 21 10](https://user-images.githubusercontent.com/5502468/142906567-3ebe76ce-db43-4172-8112-59dae8185a08.png)

I'm not entirely convinced by the calculation that's being done. For some reason I was multiplying the RA difference by -1 and leaving dec difference NOT inverted. It's actually the other way round.  Here's our friend [Wolf359](https://star.pst.qub.ac.uk/sne/atlas4/candidate/1105623201065953200/).

**Comment by thespacedoctor** [comment]
Super!
